### ISSUE TITLE
Settings Multi-select boxes unuseable

### ISSUE THREAD

**Issue by AcriCAA** [CfABrigadePhiladelphia/CyclePhilly-iOS-app#2]
I think this is a glitch with iOS 8 but, in the "settings" section of the app, the multi-select boxes (Home income, cycle frequency, rider type, rider history) are un-useable.  When you select a category, a blank translucent box on the bottom pops up and you cannot select anything.  It also basically renders the entire app un-useable. I've seen this happen in other apps post-iOS 8.  Not sure if there is a fix.

![img_3474](https://cloud.githubusercontent.com/assets/4731092/4636477/0a628dc0-53e3-11e4-92ee-e575824f7681.PNG)

**Comment by erpupone468** [comment]
UIActionsheet controls this and it is deprecated because Apple decided to just break it: 

http://stackoverflow.com/questions/24366437/add-uipickerview-in-uiactionsheet-from-ios-8-not-working

possible solution which I think would work with cocoapods: 

https://github.com/skywinder/ActionSheetPicker-3.0

**Comment by flibbertigibbet** [comment]
Nice find!

**Comment by flibbertigibbet** [comment]
Closed with 152df7ba2e803aaaab4d379712055ce7efbb6cdb
